package Telas;

import Telas.CadastroUser;
import Telas.MenuAdministrador;
import database.Banco;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.usuario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author Andrei
 */
public class ListarUsuarios extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdministrador.class.getName());

    /**
     * Creates new form ListarUsuarios
     */
    public ListarUsuarios(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        InicializarTabela();
        ConfigurarCampoPesquisa();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                confirmarSaida();
            }
        });
    }

    private void confirmarSaida() {
        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente voltar para a tela principal?",
                "Confirmar Saída",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
            new Principal().setVisible(true);
        }
    }

    public void InicializarTabela() throws Exception {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("#");
        modelo.addColumn("ID");
        modelo.addColumn("Nome");
        modelo.addColumn("Email");
        modelo.addColumn("Permissão");

        Banco dao = new Banco();
        List<usuario> lista = dao.Listar();
        int sequencia = 1;
        for (usuario c : lista) {
            modelo.addRow(new Object[]{
                sequencia++,
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getPermissao(),});
        }

        jTable1.setModel(modelo);
        RowSorter<TableModel> sorter = new TableRowSorter<>(modelo);
        jTable1.setRowSorter(sorter);
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(1));
        jTextField1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Usuarios Cadastrados");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Adicionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Pesquisar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            row = jTable1.convertRowIndexToModel(row);
            int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 1).toString());

            int confirmar = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja remover este usuário?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirmar == JOptionPane.YES_OPTION) {
                try {
                    Banco dao = new Banco();
                    dao.Remover(id);

                    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                    modelo.removeRow(row);

                    JOptionPane.showMessageDialog(
                            this,
                            "Usuário removido com sucesso!",
                            "Sucesso",
                            JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Falha ao remover: " + e.getMessage(),
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um usuário na tabela",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        confirmarSaida();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:                                        
    int row = jTable1.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Selecione um usuário para editar.");
        return;
    }

    row = jTable1.convertRowIndexToModel(row);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    int id = Integer.parseInt(model.getValueAt(row, 1).toString());
    String nome = model.getValueAt(row, 2).toString();
    String email = model.getValueAt(row, 3).toString();
    int permissao = (int) model.getValueAt(row, 4); 

    String novoNome;
    do {
        novoNome = (String) JOptionPane.showInputDialog(
                this, "Editar nome:", "Editar Nome",
                JOptionPane.PLAIN_MESSAGE, null, null, nome);

        if (novoNome == null) {
            return; 
        }
        if (novoNome.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome não pode ser vazio!");
        }
    } while (novoNome.trim().isEmpty());


    String novoEmail;
    boolean emailValido;
    do {
        emailValido = true;
        novoEmail = (String) JOptionPane.showInputDialog(
                this, "Editar email:", "Editar Email",
                JOptionPane.PLAIN_MESSAGE, null, null, email);

        if (novoEmail == null) {
            return;
        }
        if (novoEmail.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "E-mail não pode ser vazio!");
            emailValido = false;
        } else if (!novoEmail.contains("@")
                || novoEmail.indexOf("@") >= novoEmail.length() - 1
                || !novoEmail.substring(novoEmail.indexOf("@")).contains(".")) {
            JOptionPane.showMessageDialog(this,
                    "E-mail inválido! Deve conter '@' e um domínio (ex: usuario@dominio.com)");
            emailValido = false;
        }
    } while (!emailValido);

   
    String novaSenha = (String) JOptionPane.showInputDialog(
            this, "Nova senha (deixe em branco para manter a atual):",
            "Editar Senha", JOptionPane.PLAIN_MESSAGE);

  
    String mensagemConfirmacao = "Confirmar atualização do usuário?\n\n"
            + "ID: " + id + "\n"
            + "Nome: " + novoNome + "\n"
            + "E-mail: " + novoEmail + "\n"
            + "Permissão: " + permissao + "\n" 
            + (novaSenha != null && !novaSenha.trim().isEmpty()
            ? "Senha: ***** (alterada)\n"
            : "Senha: (mantida)\n");

    int confirm = JOptionPane.showConfirmDialog(
            this,
            mensagemConfirmacao,
            "Confirmação",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            Banco dao = new Banco();
            usuario usuarioAtualizado = new usuario();
            usuarioAtualizado.setId(id);
            usuarioAtualizado.setNome(novoNome);
            usuarioAtualizado.setEmail(novoEmail);
            usuarioAtualizado.setPermissao(permissao); 

            if (novaSenha != null && !novaSenha.trim().isEmpty()) {
                usuarioAtualizado.setSenha(novaSenha);
            }

            dao.Atualizar(usuarioAtualizado);
            JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!");
            InicializarTabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao atualizar usuário: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CadastroUser tela = new CadastroUser(this, true, true);
        tela.setLocationRelativeTo(this);

        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                try {
                    InicializarTabela();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(ListarUsuarios.this,
                            "Erro ao atualizar a tabela: " + ex.getMessage(),
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        tela.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Pesquisar() {
        DefaultTableModel modelo
                = (DefaultTableModel) jTable1.getModel();
        TableRowSorter filtro = new TableRowSorter(modelo);
        String buscar = jTextField1.getText();
        if (buscar.length() == 0) {
            filtro.setRowFilter(null);
        } else {
            filtro.setRowFilter(RowFilter.regexFilter(buscar));
        }
        jTable1.setRowSorter(filtro);
    }

    private void ConfigurarCampoPesquisa() {
        jTextField1.getDocument().addDocumentListener(
                new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                Pesquisar();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                Pesquisar();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                Pesquisar();
            }
        }
        );

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ListarUsuarios dialog = null;
                try {
                    dialog = new ListarUsuarios(new javax.swing.JFrame(), true);
                } catch (Exception ex) {
                    System.getLogger(ListarUsuarios.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
