/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Telas;

import database.CarroDAO;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.carros;
import Telas.StatusCarro;

/**
 *
 * @author Andrei
 */
public class MenuAdministrador extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdministrador.class.getName());

    /**
     * Creates new form MenuComum
     */
    public MenuAdministrador(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        InicializarTabela();
        ConfigurarCampoPesquisa();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                confirmarSaida();
            }
        });
    }

    private double parsePreco(String input) {
        String valorFormatado = input.replace(",", ".");
        return Double.parseDouble(valorFormatado);
    }

    private void confirmarSaida() {
        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente voltar para a tela principal?",
                "Confirmar Saída",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
            new Principal().setVisible(true);
        }
    }

    public void InicializarTabela() throws Exception {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("#");
        modelo.addColumn("ID");
        modelo.addColumn("Modelo");
        modelo.addColumn("Marca");
        modelo.addColumn("Ano");
        modelo.addColumn("Preço");
        modelo.addColumn("Status");

        CarroDAO dao = new CarroDAO();
        List<carros> listar = dao.listar();
        int sequencia = 1;
        for (carros c : listar) {
            String st = "Á venda";
            if (c.getStatus() == 2) {
                st = "Reservado";
            } else if (c.getStatus() == 3) {
                st = "Vendido";
            }
            modelo.addRow(new Object[]{
                sequencia++,
                c.getId(),
                c.getModelo(),
                c.getMarca(),
                c.getAno(),
                c.getPreco(),
                st,
                String.format("R$ %,.2f", c.getPreco())
            });
        }

        jTable1.setModel(modelo);

        jTable1.removeColumn(jTable1.getColumnModel().getColumn(1));

        RowSorter<TableModel> sorter = new TableRowSorter<>(modelo);
        jTable1.setRowSorter(sorter);

        jTextField1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Catálogo de carros");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Recarregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Remover");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Adicionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Pesquisar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // BOTÃO DE EDITAR
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um carro para editar.");
            return;
        }
        row = jTable1.convertRowIndexToModel(row);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int id = Integer.parseInt(model.getValueAt(row, 1).toString());
        String modelo = model.getValueAt(row, 2).toString();
        String marca = model.getValueAt(row, 3).toString();
        int ano = Integer.parseInt(model.getValueAt(row, 4).toString());

        Object value = model.getValueAt(row, 5);
        String precoStr;
        if (value instanceof Number) {
            precoStr = value.toString();
        } else {
            precoStr = value.toString()
                    .replace("R$", "")
                    .replace(".", "")
                    .replace(",", ".")
                    .trim();
        }
        double preco = Double.parseDouble(precoStr);

        String statusStr = model.getValueAt(row, 6).toString();
        int statusAtual;
        switch (statusStr) {
            case "Reservado":
                statusAtual = 2;
                break;
            case "Vendido":
                statusAtual = 3;
                break;
            default:
                statusAtual = 1; // "Á venda"
        }

        String novoModelo = (String) JOptionPane.showInputDialog(
                this, "Editar modelo:", "Editar Modelo",
                JOptionPane.PLAIN_MESSAGE, null, null, modelo);

        if (novoModelo == null || novoModelo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Modelo não pode ser vazio");
            return;
        }

        String novaMarca = (String) JOptionPane.showInputDialog(
                this, "Editar marca:", "Editar Marca",
                JOptionPane.PLAIN_MESSAGE, null, null, marca);

        if (novaMarca == null || novaMarca.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Marca não pode ser vazia");
            return;
        }

        String strAno = (String) JOptionPane.showInputDialog(
                this, "Editar ano:", "Editar Ano",
                JOptionPane.PLAIN_MESSAGE, null, null, ano);

        int novoAno;
        try {
            novoAno = Integer.parseInt(strAno);
            if (novoAno <= 1900 || novoAno > java.time.Year.now().getValue() + 1) {
                JOptionPane.showMessageDialog(this, "Ano inválido");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ano deve ser um número válido");
            return;
        }

        String strPreco = (String) JOptionPane.showInputDialog(
                this, "Editar preço:", "Editar Preço",
                JOptionPane.PLAIN_MESSAGE, null, null, String.format("%.2f", preco));

        double novoPreco;
        try {
            novoPreco = Double.parseDouble(strPreco.replace(",", "."));
            if (novoPreco <= 0) {
                JOptionPane.showMessageDialog(this, "Preço deve ser positivo");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Preço inválido");
            return;
        }

        int st = StatusCarro.showStatusDialog(this);

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Confirmar atualização do carro?\n"
                + "Modelo: " + novoModelo + "\n"
                + "Marca: " + novaMarca + "\n"
                + "Ano: " + novoAno + "\n"
                + "Preço: R$ " + String.format("%.2f", novoPreco) + "\n"
                + "Status: " + (st == 1 ? "Á venda" : st == 2 ? "Reservado" : "Vendido"),
                "Confirmação",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {

                CarroDAO dao = new CarroDAO();
                carros carroAtualizado = new carros(id, novoModelo, novaMarca, novoAno, novoPreco, st);

                if (dao.atualizar(carroAtualizado)) {
                    JOptionPane.showMessageDialog(this, "Carro atualizado com sucesso!");
                    InicializarTabela();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Falha ao atualizar carro",
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Erro ao atualizar: " + e.getMessage(),
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um carro para editar.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            InicializarTabela();
        } catch (Exception ex) {
            System.getLogger(MenuAdministrador.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        JOptionPane.showMessageDialog(this, "Tabela atualizada com sucesso!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            row = jTable1.convertRowIndexToModel(row);

            // Obtém o ID da coluna 1 (coluna 0 é a numeração sequencial)
            int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 1).toString());

            int confirmar = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja remover este carro?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirmar == JOptionPane.YES_OPTION) {
                try {
                    CarroDAO dao = new CarroDAO();
                    boolean removido = dao.remover(id);

                    if (removido) {
                        JOptionPane.showMessageDialog(
                                this,
                                "Carro removido com sucesso!",
                                "Sucesso",
                                JOptionPane.INFORMATION_MESSAGE);
                        InicializarTabela();
                    } else {
                        JOptionPane.showMessageDialog(
                                this,
                                "Nenhum carro foi removido. Verifique o ID.",
                                "Aviso",
                                JOptionPane.WARNING_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Erro ao remover carro: " + e.getMessage(),
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um carro na tabela para remover.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            String modelo = null;
            do {
                modelo = JOptionPane.showInputDialog(this, "Modelo:");
                if (modelo == null) {
                    return; // Usuário cancelou
                }
                if (modelo.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Modelo não pode estar vazio.");
                }
            } while (modelo.trim().isEmpty());

            String marca = null;
            do {
                marca = JOptionPane.showInputDialog(this, "Marca:");
                if (marca == null) {
                    return;
                }
                if (marca.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Marca não pode estar vazia.");
                }
            } while (marca.trim().isEmpty());

            int ano = -1;
            while (ano <= 0) {
                String inputAno = JOptionPane.showInputDialog(this, "Ano:");
                if (inputAno == null) {
                    return;
                }
                try {
                    ano = Integer.parseInt(inputAno);
                    if (ano <= 1900 || ano > java.time.Year.now().getValue() + 1) {
                        JOptionPane.showMessageDialog(this, "Ano inválido");
                        ano = -1;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Ano deve ser um número válido");
                    ano = -1;
                }
            }

            double preco = -1;
            while (preco < 0) {
                String inputPreco = JOptionPane.showInputDialog(this, "Preço:");
                if (inputPreco == null) {
                    return;
                }
                try {
                    preco = parsePreco(inputPreco);
                    if (preco < 0) {
                        JOptionPane.showMessageDialog(this, "Preço deve ser positivo.");
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Digite um valor numérico válido para o preço. Use ponto ou vírgula como separador decimal.");
                    preco = -1;
                }
            }

            int status = 1;

            carros carro = new carros(0, modelo, marca, ano, preco, status);
            CarroDAO dao = new CarroDAO();
            dao.inserir(carro);
            InicializarTabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void Pesquisar() {
        DefaultTableModel modelo
                = (DefaultTableModel) jTable1.getModel();
        TableRowSorter filtro = new TableRowSorter(modelo);
        String buscar = jTextField1.getText();
        if (buscar.length() == 0) {
            filtro.setRowFilter(null);
        } else {
            filtro.setRowFilter(RowFilter.regexFilter(buscar));
        }
        jTable1.setRowSorter(filtro);
    }

    private void ConfigurarCampoPesquisa() {
        jTextField1.getDocument().addDocumentListener(
                new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                Pesquisar();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                Pesquisar();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                Pesquisar();
            }
        }
        );

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MenuAdministrador dialog = null;
                try {
                    dialog = new MenuAdministrador(new javax.swing.JFrame(), true);
                } catch (Exception ex) {
                    System.getLogger(MenuAdministrador.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
